instal---
title: "Felix_EDA"
author: "Yifei Liu"
date: 2023/11/25
output: github_document
---

```{r setup, message = FALSE}
library(tidyverse)
library(modelr)
library(purrr)
library(corrplot)
library(FactoMineR)
library(factoextra)
```


```{r}
#load mortality dataset
mort_data =
  read_csv("mortality_data_cleaned.csv") |> 
  janitor::clean_names() |>
  select(-group, everything())
```


```{r fig.width = 10, fig.height = 10}
#select patient outcome and complications
com_data =
  mort_data |>
  select(outcome, hypertensive:copd)
#show correlation
corrplot(cor(com_data), type = "upper", diag = FALSE)
```

Interpretation:\
 - `outcome` seems strongly connected with `deficiencyanemias`, `renal_failure`.\ 
 - `hypertensive` shows strong correlation with `hyperlipemia` and `renal_failure`.\
 - `diabetes` shows strong correlation with `renal_failure`.\
 - `hyperlipemia` also shows strong correlation with `renal_failure`.\

```{r fig.width = 10, fig.height = 10}
#select patient outcome and vital signs
sign_data =
  mort_data |>
  select(outcome, heart_rate:ef)
#show correlation
corrplot(cor(sign_data), type = "upper", diag = FALSE)
```


```{r}
#linear model for complications
model_com = glm(outcome ~ ., data = com_data)
summary(model_com)

model_com_se = lm(outcome ~ ., data = com_data) |>
  step(direction = "both", trace = FALSE)
summary(model_com_se)
```


```{r}
#generalized linear model for complications
model_com_glm = glm(outcome ~ ., data = com_data)
summary(model_com_glm)

model_com_glm_se = glm(outcome ~ ., data = com_data) |>
  step(direction = "both", trace = FALSE)
summary(model_com_glm_se)
```


```{r}
#linear model for vital signs
model_sign = lm(outcome ~ ., data = sign_data)
summary(model_sign)

model_sign_se = lm(outcome ~ ., data = sign_data) |>
  step(direction = "both", trace = FALSE)
summary(model_sign_se)
```


```{r}
#cross-validation for complications
cv_com =
  modelr::crossv_mc(com_data, 10)

cv_com_rmse =
  cv_com |>
  mutate(
    lm_cv_com = map(cv_com$train, 
                         \(df) lm(outcome ~ ., data = (df)) |>
                           step(direction = "both", trace = FALSE)),
    glm_cv_com = map(cv_com$train, 
                         \(df) glm(outcome ~ ., data = (df)) |>
                           step(direction = "both", trace = FALSE)),
    lm_cv_pca1 = map(cv_com$train, 
                         \(df) glm(outcome ~ renal_failure + hypertensive + diabetes + hyperlipemia, data = (df))),
    lm_cv_pca2 = map(cv_com$train, 
                         \(df) glm(outcome ~ chd_with_no_mi + depression + copd + atrialfibrillation, data = (df)))
  ) |>
  mutate(
    errs_lm_com = purrr::map2_dbl(lm_cv_com, cv_com$test, rmse),
    errs_glm_com = purrr::map2_dbl(glm_cv_com, cv_com$test, rmse),
    errs_pca1 = purrr::map2_dbl(lm_cv_pca1, cv_com$test, rmse),
    errs_pca2 = purrr::map2_dbl(lm_cv_pca2, cv_com$test, rmse)
  )

cv_com_rmse |>
  select(lm_com = errs_lm_com,
         glm_com = errs_glm_com,
         lm_pca1 = errs_pca1,
         lm_pca2 = errs_pca2) |>
  pivot_longer(everything(), 
               names_to = "models",
               values_to = "rmse") |>
  mutate(model = factor(models, levels = c("lm_com", "glm_com", "lm_pca1", "lm_pca2"))) |>
  ggplot(aes(x = model, y = rmse)) +
  geom_violin() +
  labs(x = "Models", y = "rmse", title = "Cross-Validated Prediction Error") +
  theme_minimal()
```


```{r}
#pca for complications
com_names = 
  com_data |>
  select(hypertensive:copd) |>
  colnames()

#pca using R build-in function prcomp()
vars_com = com_data[, com_names]
pca_res_com = prcomp(vars_com, scale. = TRUE)
summary(pca_res_com)

#pca using packages `FactoMineR`, `factoextra`
com = com_data |> select(-outcome)
res_pca_com = PCA(com, scale.unit = TRUE, graph = TRUE)
#PCA() function would do the data standardization automatically.
#keep 5 dimensions as result.

get_eigenvalue(res_pca_com)
#`variance.percent` explains the percentage of change. 70% would be adequate.

#scree plot
fviz_eig(res_pca_com, addlabels = TRUE, ylim = c(0, 20))
#visualize the contributions of each dimension.

#result
var_com <- get_pca_var(res_pca_com) 
var_com$coord
#shown by correlation

fviz_pca_var(res_pca_com, col.var = "contrib", gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"))
#based on above results (`var_com$coord`)
#basically,
#(a) positive correlated variables are grouped together,
#(b) negative correlated variables are located on opposite sides of the origin,
#(c) the distance between the variable and the origin measures the quality of the variable. Variables that are far from the origin are well represented.

corrplot(var_com$cos2, is.corr=FALSE)
#shows the quality of variables.

var_com$contrib
#shown by contribution

fviz_contrib(res_pca_com, choice = "var", axes = 1, top = 10)
fviz_contrib(res_pca_com, choice = "var", axes = 1:5, top = 10)

#colored individuals
fviz_pca_ind(res_pca_com,
             geom.ind = "point",
             col.ind = as.character(com_data$outcome),
             palette = c("#00AFBB", "#FC4E07"),
             addEllipses = TRUE,
             legend.title = "Groups")
```


```{r}
#pca for vital signs
sign_names = 
  sign_data |>
  select(heart_rate:ef) |>
  colnames()

#pca using R build-in function prcomp()
vars_sign = sign_data[, sign_names]
pca_res_sign = prcomp(vars_sign, scale. = TRUE)
summary(pca_res_sign)

#pca using packages `FactoMineR`, `factoextra`
sign = sign_data |> select(-outcome)
res_pca_sign = PCA(sign, scale.unit = TRUE, graph = TRUE)
#PCA() function would do the data standardization automatically.
#keep 5 dimensions as result.

get_eigenvalue(res_pca_sign)
#`variance.percent` explains the percentage of change. 70% would be adequate.

#scree plot
fviz_eig(res_pca_sign, addlabels = TRUE, ylim = c(0, 20))
#visualize the contributions of each dimension.

#result
var_sign <- get_pca_var(res_pca_sign) 
var_sign$coord
#shown by correlation

fviz_pca_var(res_pca_sign, col.var = "contrib", gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"))
#based on above results (`var_com$coord`)

corrplot(var_sign$cos2, is.corr=FALSE)
#shows the quality of variables.

var_sign$contrib
#shown by contribution

fviz_contrib(res_pca_sign, choice = "var", axes = 1, top = 10)
fviz_contrib(res_pca_sign, choice = "var", axes = 1:5, top = 10)

#colored individuals
fviz_pca_ind(res_pca_sign,
             geom.ind = "point",
             col.ind = as.character(sign_data$outcome),
             palette = c("#00AFBB", "#FC4E07"),
             addEllipses = TRUE,
             legend.title = "Groups")
```


